import { ApifyClient } from 'apify-client';
import { NextResponse } from 'next/server';

export async function GET(request) {
  try {
    const client = new ApifyClient({
      token: process.env.APIFY_API_TOKEN,
    });

    const input = {
      "downloadSubtitles": false,
      "hasCC": false,
      "hasLocation": false,
      "hasSubtitles": false,
      "is360": false,
      "is3D": false,
      "is4K": false,
      "isBought": false,
      "isHD": false,
      "isHDR": false,
      "isLive": false,
      "isVR180": false,
      "maxResultStreams": 0,
      "maxResults": 10,
      "maxResultsShorts": 0,
      "preferAutoGeneratedSubtitles": false,
      "startUrls": [
        {
          "url": "https://www.youtube.com/@AgênciaBrasília-k9w/videos"
        }
      ]
    };

    // start() inicia o actor sem bloquear para esperar a resposta 
    // Ideal para rotas Vercel Cron
    const run = await client.actor("h7sDV53CddomktSi5").start(input);
    
    return NextResponse.json({ 
        success: true, 
        message: "Operação iniciada com sucesso. A Apify raspará os últimos vídeos em background.", 
        runId: run.id 
    });
  } catch(error) {
    console.error("Erro no cron:", error);
    return NextResponse.json({ success: false, error: error.message }, { status: 500 });
  }
}
